"""Pydantic schemas for BiteBuddy."""

from app.schemas.chat import (
    AgentInput,
    AgentReply,
    AgentConflict,
    ChatMessage,
    ChatRequest,
    IngredientSubstitution,
    PreferenceSnapshot,
    RecipeMatch,
    RetrievalTrace,
    UserProfile,
)
from app.schemas.auth import (
    AuthResponse,
    AuthUser,
    FavoriteRecipeItem,
    FavoriteSaveRequest,
    HistoryItem,
    HistorySaveRequest,
    LoginRequest,
    MessageResponse,
    RegisterResponse,
    RegisterRequest,
    ResendOtpRequest,
    VerifyEmailRequest,
)
from app.schemas.recipe import RecipeDocument, RecipeRecord

__all__ = [
    "AgentInput",
    "AgentReply",
    "AgentConflict",
    "ChatMessage",
    "ChatRequest",
    "IngredientSubstitution",
    "PreferenceSnapshot",
    "RecipeMatch",
    "RegisterRequest",
    "RegisterResponse",
    "VerifyEmailRequest",
    "ResendOtpRequest",
    "MessageResponse",
    "LoginRequest",
    "AuthUser",
    "AuthResponse",
    "FavoriteRecipeItem",
    "FavoriteSaveRequest",
    "HistoryItem",
    "HistorySaveRequest",
    "RecipeDocument",
    "RecipeRecord",
    "RetrievalTrace",
    "UserProfile",
]
